export const avatarImages: { [key: string]: string } = {
  zalmai: "/images/profile/Zalmai.jpg",
  akhtar: "/images/profile/Akhtar.jpg",
  aman: "/images/profile/Aman.jpg",
  alam: "/images/profile/Alam.jpg",
  dawood: "/images/profile/Dawood.jpg",
  faizMohammad: "/images/profile/FaizMohammad.jpg",
  hamid: "/images/profile/Hamid.jpg",
  haroon: "/images/profile/Haroon.jpg",
  hizbullah: "/images/profile/Hizbullah.jpg",
  ismail: "/images/profile/Ismail.jpg",
  javid: "/images/profile/Javid.jpg",
  lajbar: "/images/profile/Lajbar.jpg",
  malik: "/images/profile/Malik.jpg",
  mohammadullah: "/images/profile/Mohammadullah.jpg",
  mustafa: "/images/profile/Mustafa.jpg",
  najibullah: "/images/profile/Najibullah.jpg",
  abdulqayoum: "/images/profile/Qayoum.jpg",
  tahir: "/images/profile/Tahir.jpg",
};
